
 
http://localhost:8080/api/v1


### ADMIN -----------------------------------------------------------

### Register as an admin ###

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name": "Admin",
    "username": "Admin 1",
    "email": "nicolejoyesposo@gmail.com",
    "password": "12345",
    "role": "admin"
}


### Activate admin account ###

http://localhost:8080/api/v1/auth/activate/#


### Login admin account ###

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "nicolejoyesposo@gmail.com",
    "password": "12345"
}


### View all users registered / Admin only ###

http://localhost:8080/api/v1/auth/users
authorization: Bearer #


### Admin can view their own data ###

http://localhost:8080/api/v1/auth/users/#
authorization: Bearer #


### Admin can edit their own data ###

PUT http://localhost:8080/api/v1/auth/users/#
Content-Type: application/json
authorization: Bearer #

{
    "name": "Pretty Admin"
}


### Admin can't edit the data of other users ###

PUT http://localhost:8080/api/v1/auth/users/#
Content-Type: application/json
authorization: Bearer #

{
    "name": "Userzzz"
}


### Admin can delete other users

DELETE http://localhost:8080/api/v1/auth/users/#
Content-Type: application/json
authorization: Bearer #




### USERS -----------------------------------------------------------

### Register as a new user

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name": "Christopher Reid   ",
    "username": "chrissybels",
    "email": "istian@gmail.com",
    "password": "12345"
}


### Activate user account ###

http://localhost:8080/api/v1/auth/activate/#


### Login as a user ##

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "istian@gmail.com",
    "password": "12345"
}


### User should not be able to see the list of users registered ##
### Forbidden ##

http://localhost:8080/api/v1/auth/users
authorization: Bearer #


### User can view their own data ##

http://localhost:8080/api/v1/auth/users/#
authorization: Bearer #


### User can't view the data of the admin
### Forbidden ##

http://localhost:8080/api/v1/auth/users/#
authorization: Bearer #


### User can edit their own date

PUT http://localhost:8080/api/v1/auth/users/#
Content-Type: application/json
authorization: Bearer #

{
    "name": "Istian Reidzzzzz"
}


### User should not be able to edit the admin's info ##
### Forbidden ##

http://localhost:8080/api/v1/auth/users/#
authorization: Bearer #

{
    "name": "Adminzzz"
}


### User can delete their own account ##

DELETE http://localhost:8080/api/v1/auth/users/#
Content-Type: application/json
authorization: Bearer #
